import { NextResponse } from 'next/server';

export const dynamic = 'force-static';

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.nazafahriyadh.com/</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/about</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/areas</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/offers</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/villa-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/home-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/sofa-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/majlis-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/marble-polishing-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/deep-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/areas/north-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/areas/east-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/areas/west-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/areas/center-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/areas/south-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/faq</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/contact</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/privacy-policy</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/terms</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/water-tank-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/ac-duct-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/facade-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/services/office-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=sofa-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/sofa-majlis-steam-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=home-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/riyadh-dust-storm-cleaning-guide</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/ac-duct-deep-cleaning-energy-saving</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=majlis-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/east-west-south-riyadh-neighborhoods-cleaning-guide</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/north-riyadh-villas-cleaning-masterguide</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/marble-care-and-crystallization</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/post-construction-deep-cleaning-checklist</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/water-tank-cleaning-and-sanitization-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=villa-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=office-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?area=south-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?area=east-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=deep-cleaning-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?area=center-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?service=marble-polishing-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?area=north-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/request-service?area=west-riyadh</loc>
    <lastmod>2026-09-23</lastmod>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/best-villa-cleaning-company-riyadh</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/cheapest-cleaning-company-riyadh</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/best-cleaning-services-companies-guide-riyadh</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/cleaning-company-riyadh-stages-execution</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/palace-cleaning-company-riyadh</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/tips-cleaning-stone-glass-facades-villas</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
  <url>
    <loc>https://www.nazafahriyadh.com/blog/inspect-sterilize-disinfect-villa-water-tanks</loc>
    <lastmod>2026-09-28</lastmod>
    <priority>0.85</priority>
  </url>
</urlset>`;

export async function GET() {
  return new NextResponse(sitemapXml.trim(), {
    status: 200,
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400, stale-while-revalidate=43200',
    },
  });
}
